### ISSUE TITLE
umami 2.x migration - make 2.9.0 compatible

### ISSUE THREAD

**Issue by boly38** [boly38/umami-api-client#15]
this client has not been updated since long time (ex. was compatible with umami `1.40` and now umami is `2.9.0`)

For information typical error i for [boly38](https://github.com/boly38)/[action-umami-report](https://github.com/boly38/action-umami-report) s now
````
TypeError: t.map is not a function
````

In addition, I noticed that jakobbouchard/umami-api-client seems not migrated to 2.x too

so todo tasks :
- [x] update the client and test to be compatible with `2.9.0` version
- [x] report here the change between old an new client calls to help jakobbouchard/umami-api-client update
- [x] create a new release => ✅ `v2.0.9` [release](https://github.com/boly38/umami-api-client/releases/tag/v2.0.9)
- [x] check umami doc again (via #17) & create an issue if relevant => umami-software/website#150
- [x] create action-umami-report ticket to make them green again => boly38/action-umami-report#46
- [x] create a jakobbouchard/umami-api-client issue to trigger update on the other client too : => jakobbouchard/umami-api-client#84

**Comment by boly38** [comment]
Changes in API and so in umami client:
- `/api/website/` become `/api/websites/`
- site data keys have changes, ex. from `'website_id', 'website_uuid', 'name', 'domain', 'created_at'` to `'id', 'name', 'domain', 'createdAt'`, and so a period change from `start_at, end_at ` to ` startAt, endAt`
- login failed message moved from `401 - Login failed - 401 Unauthorized` to `401 - Login failed - message.incorrect-username-password`
- get sites response data now include a new level where array of websites is located in `data` attribute. ⚠️ Note that [umami doc](https://umami.is/docs/websites-api) is no up-to-date to (maybe check and create an umami issue)
- ⚠️ note that the upgrade is limited to current scope and this list may not be exhaustive
